# Jekyll Configuration for GitHub Pages

# Site settings
title: LiCycle AI
description: Regulatory guidance for battery recycling businesses based on CSRD and CBAM legislation
baseurl: "/LiCycle-AI" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# Enable relative URLs for GitHub Pages
relative_urls: true

# Sass settings
sass:
  style: compressed

# Collections
collections:
  - sections

# Default layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
